services:
  db:
    image: 'postgres:latest'
    container_name: postgres-planetarium
    env_file:
      - ../src/.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_planetarium_data:/var/lib/postgresql/data
    networks:
      - planetarium-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_planetarium_data:
    driver: local

networks:
  planetarium-network:
    driver: bridge
