# Generated by Django 5.1.6 on 2025-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_url",
            field=models.URLField(
                default="https://checkout.stripe.com/c/pay/cs_test_a1vKJko64D02P9faCzDAObaWKIr5djVQZdLEafQ791pVHhMXEKSC3RCML6#fidkdWxOYHwnPyd1blpxYHZxWjA0VHN9T31NdnZVNk1EXUt%2Ff2AxT0d1UnQyfGJic1VSazA2SVRdX3FiQk81QlBLTFJcR1NxYlNxajU1bjdcVjd2STJPVU1vQ3FzYWpjck4wNkJhMG5EQTxANTVOYDJ3SmF3bScpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",
                max_length=510,
            ),
            preserve_default=False,
        ),
    ]
