# Generated by Django 5.1.6 on 2025-02-22 12:07

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="astronomy_show",
            new_name="show",
        ),
        migrations.AddField(
            model_name="show",
            name="poster",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.show_poster_file_path
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_themes",
            field=models.ManyToManyField(
                related_name="shows", to="planetarium.showtheme"
            ),
        ),
    ]
