# Generated by Django 5.1.6 on 2025-02-23 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_rename_astronomy_show_event_show_show_poster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dome",
            name="rows",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="dome",
            name="seats_in_row",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
